version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    entrypoint: ['/urs/src/app/entrypoint.sh']
    image: stock-app-flask-api
    volumes:
      - .:/urs/src/app
    environment:
      - FLASK_APP=api/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=${APP_SETTINGS}
      - DATABASE_URL=${DATABASE_URL}
      - TESTING_DATABASE_URL=${TESTING_DATABASE_URL}
      - IEX_API_TOKEN=${IEX_API_TOKEN}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 5000:5000

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: stock-app-react-client
    depends_on:
      - api

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: stock-app-postgres-db
    expose:
      - 5432
    ports:
      - 8000:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgAdmin:
    container_name: stock-app-postgres-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
