version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/urs/src/app/entrypoint.sh']
    volumes:
      - .:/urs/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=server/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=server.config.DevelopmentConfig
      - DATABASE_URL=${DATABASE_URL}
      - TESTING_DATABASE_URL=${TESTING_DATABASE_URL}
      - IEX_API_TOKEN=${IEX_API_TOKEN}
    depends_on:
      - db
    restart: unless-stopped


  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}