version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_ENV=development
    volumes:
      - .:/urs/src/app
    ports:
      - 5004:5000

  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
