FROM node:17-alpine AS build-step
WORKDIR /client
ENV PATH /app/node_modules/.bin:$PATH
COPY ./client/package.json ./
COPY ./client/src ./src
COPY ./client/public ./public
RUN npm i
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-step /client/build /urs/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
