version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/urs/src/app/entrypoint.sh']
    volumes:
      - .:/urs/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=server.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/api_dev
      - TESTING_DATABASE_URL=postgresql://postgres:postgres@db:5432/api_test
    depends_on:
      - db

  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
