version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    entrypoint: ['/urs/src/app/entrypoint.sh']
    image: stock-app-flask-server
    volumes:
      - .:/urs/src/app
    environment:
      - FLASK_APP=server/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=server.config.DevelopmentConfig
      - DATABASE_URL=${DATABASE_URL}
      - TESTING_DATABASE_URL=${TESTING_DATABASE_URL}
      - IEX_API_TOKEN=${IEX_API_TOKEN}
    depends_on:
      - db
    restart: unless-stopped

  db:
    build:
      context: ./server/db
      dockerfile: Dockerfile.db
    image: stock-app-postgres-db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: stock-app-react-client
    volumes:
      - ./client:/client
    depends_on:
      - server
    ports:
      - 3000:80
